/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Dav(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/4D JORGE PIERNAS.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Plano001"
          castShadow
          receiveShadow
          geometry={nodes.Plano001.geometry}
          material={materials["Material.002"]}
          position={[-0.06, 0.14, -0.18]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Plano002"
          castShadow
          receiveShadow
          geometry={nodes.Plano002.geometry}
          material={materials["Material.002"]}
          position={[-0.06, 0.14, -0.18]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Plano003"
          castShadow
          receiveShadow
          geometry={nodes.Plano003.geometry}
          material={materials["Material.002"]}
          position={[-0.06, 0.14, -0.18]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          name="Texto"
          castShadow
          receiveShadow
          geometry={nodes.Texto.geometry}
          material={materials["Material.002"]}
          position={[0.27, -0.07, 0.02]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.63}
        />
        <mesh
          name="Texto001"
          castShadow
          receiveShadow
          geometry={nodes.Texto001.geometry}
          material={materials["Material.002"]}
          position={[-0.06, -0.07, 0.18]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.56}
        />
        <mesh
          name="Texto002"
          castShadow
          receiveShadow
          geometry={nodes.Texto002.geometry}
          material={materials["Material.002"]}
          position={[0.22, -0.02, -0.08]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.62}
        />
        <group
          name="TQ_ARD-node"
          position={[0, 0.02, -0.01]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="TQ_ARD-geom001"
            castShadow
            receiveShadow
            geometry={nodes["TQ_ARD-geom001"].geometry}
            material={materials["TQ_ARD_front.001"]}
          />
          <mesh
            name="TQ_ARD-geom001_1"
            castShadow
            receiveShadow
            geometry={nodes["TQ_ARD-geom001_1"].geometry}
            material={materials["TQ_ARD_back.001"]}
          />
          <mesh
            name="TQ_ARD-geom001_2"
            castShadow
            receiveShadow
            geometry={nodes["TQ_ARD-geom001_2"].geometry}
            material={materials["TQ_ARD_edge.001"]}
          />
        </group>
        <group name="TQ_ARD-node001" position={[-0.19, 0.02, 0]}>
          <mesh
            name="TQ_ARD-geom003"
            castShadow
            receiveShadow
            geometry={nodes["TQ_ARD-geom003"].geometry}
            material={materials["TQ_ARD_front.001"]}
          />
          <mesh
            name="TQ_ARD-geom003_1"
            castShadow
            receiveShadow
            geometry={nodes["TQ_ARD-geom003_1"].geometry}
            material={materials["TQ_ARD_back.001"]}
          />
          <mesh
            name="TQ_ARD-geom003_2"
            castShadow
            receiveShadow
            geometry={nodes["TQ_ARD-geom003_2"].geometry}
            material={materials["TQ_ARD_edge.001"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/4D JORGE PIERNAS.gltf");
